CREATE TABLE datos (
    id INT AUTO_INCREMENT PRIMARY KEY,
    edad FLOAT,
    genero VARCHAR(50)
);

INSERT INTO datos (edad, genero) VALUES
(-25, 'masculino'),
(NULL, 'femenino'),
(NULL, 'no binario'),
(35, 'masculino'),
(-42, 'femenino'),
(NULL, 'masculino'),
(NULL, 'no binario'),
(28, 'femenino'),
(-18, 'masculino'),
(NULL, 'femenino'),
(NULL, 'no binario'),
(22, 'masculino'),
(-36, 'femenino'),
(NULL, 'no binario'),
(NULL, 'masculino'),
(31, 'femenino'),
(-50, 'masculino'),
(NULL, 'femenino'),
(NULL, 'no binario'),
(40, 'masculino'),
(-60, 'femenino'),
(NULL, 'masculino'),
(NULL, 'femenino'),
(45, 'masculino'),
(-70, 'femenino'),
(NULL, 'no binario'),
(NULL, 'masculino'),
(55, 'femenino'),
(-80, 'masculino'),
(NULL, 'femenino'),
(NULL, 'no binario'),
(33, 'masculino'),
(-90, 'femenino'),
(NULL, 'no binario'),
(NULL, 'masculino'),
(27, 'femenino'),
(-100, 'masculino'),
(NULL, 'femenino'),
(NULL, 'no binario'),
(39, 'masculino'),
(-110, 'femenino'),
(NULL, 'masculino'),
(NULL, 'no binario'),
(49, 'masculino'),
(-120, 'no binario'),
(NULL, 'femenino'),
(NULL, 'masculino'),
(100, 'masculino');
